server:
  port: 9526
  #-----------------------------------日志文件-------------------------------------------------
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  file:
    path: ./logs
spring:
  #-----------------------------------数据库配置-------------------------------------------------
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 100
    maxActive: 200
    initialSize: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowMultiQueries=true&useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  #------------------------------Redis单机版配置-------------------------------------------------
  redis:
    #数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 3000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 30
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    #--------------------------Redis集群版配置-------------------------------------------------
    #    password:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
      expireSeconds: 120
      commandTimeout: 10000
      max-redirects: 3
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
#--------------------------mybatis xml配置文件-------------------------------------------------
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.madd.template.pojo
  #------------------------------------------------shiro-----------------------------------------------
shiro:
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true
